In [52]:
import numpy as np

## 2-D Array


In [53]:
a1=np.array([[11,22,33],[44,55,66],[77,88,99]])
a1

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [54]:
a2=np.matrix([[42,22,83],[11,55,36],[97,88,79]])
a2

matrix([[42, 22, 83],
        [11, 55, 36],
        [97, 88, 79]])

In [55]:
a3=np.array([311,453,520,362,230,281,672,891,421])
a4=np.reshape(a3,(3,3))
a4

array([[311, 453, 520],
       [362, 230, 281],
       [672, 891, 421]])

In [11]:
a5=np.zeros((3,3))
a5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a6=np.ones((3,3))
a6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a7=np.reshape(range(100,200,5),(4,5))
print(a7[2][1])
a7

155


array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [58]:
a7[0:2,0:4]

array([[100, 105, 110, 115],
       [125, 130, 135, 140]])

In [29]:
print(a7.transpose())

[[100 125 150 175]
 [105 130 155 180]
 [110 135 160 185]
 [115 140 165 190]
 [120 145 170 195]]


In [30]:
print(a7.ndim) #dimension

2


In [31]:
print(a7.flatten())

[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]


In [59]:
np.sort(a7,axis=0) #column

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [38]:
np.sort(a7,axis=1) #row

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [39]:
np.diagonal(a7)

array([100, 130, 160, 190])

In [44]:
a8=np.array([[115,123,120],[130,117,281],[321,564,789]])
a9=np.array([[111,123,121],[131,117,282],[321,464,989]])

In [47]:
print(a8>=a9)

[[ True  True False]
 [False  True False]
 [ True  True False]]


In [48]:
print(a8<=a9)

[[False  True  True]
 [ True  True  True]
 [ True False  True]]


In [49]:
print(a8==a9)

[[False  True False]
 [False  True False]
 [ True False False]]


In [50]:
print(a8!=a9)

[[ True False  True]
 [ True False  True]
 [False  True  True]]


In [60]:
a8+a9

array([[ 226,  246,  241],
       [ 261,  234,  563],
       [ 642, 1028, 1778]])