In [2]:

import numpy as np
#MST-2 Syllabus dictionaries,: Class,object,constructor,destructor and inheritance;File Input and Output,Numpy: Creating Arrays,
# Arrays Operations,Multidimensional Arrays. Arrays transformation,Array Concatenation, Array Math Operations, 
# Multidimensional Array and its Operations,

In [38]:
ar=np.array([11,22,33,44,55,66,77,88])
ar

array([11, 22, 33, 44, 55, 66, 77, 88])

In [39]:
arr=np.array(['a','b','c','d','e'])
arr

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [40]:
arrr=np.array(['java','python','sql','c','excel','tableau'])
arrr

array(['java', 'python', 'sql', 'c', 'excel', 'tableau'], dtype='<U7')

In [41]:
ar2=np.array([[11,22,33],[44,55,66],[77,88,99]])
ar2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

using view() function to create a new array from an existing array
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [42]:
arr4=ar.view()
print(arr4)

[11 22 33 44 55 66 77 88]


In [77]:
arrc=ar.copy()
print(arrc)

[11 22 33 44 55 66 77 88]


In [44]:
arr5=np.arange(10)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
arr6=np.arange(10,dtype=np.float)
print(arr6)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


C:\Users\DELL\AppData\Local\Temp/ipykernel_10316/1337032726.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr6=np.arange(10,dtype=np.float)


In [46]:
#linespace(start,end,number of values between the given range)
arr7=np.linspace(10,60,4)
print(arr7)

[10.         26.66666667 43.33333333 60.        ]


In [47]:
arr8=np.linspace(10.5,56.7,4)
print(arr8)

[10.5 25.9 41.3 56.7]


In [78]:
arr9=np.zeros(4)
arr9

array([0., 0., 0., 0.])

In [79]:
arr10=np.ones(5)
arr10

array([1., 1., 1., 1., 1.])

In [50]:
print(ar2.shape)

(3, 3)


In [51]:
print(ar2.size)

9


In [52]:
print(np.mean(ar2))

55.0


In [53]:
print(np.median(ar2))

55.0


In [54]:
print(np.sum(ar2))

495


In [55]:
print(np.prod(ar2))

83466368


In [56]:
print(np.cov(ar2))

[[121. 121. 121.]
 [121. 121. 121.]
 [121. 121. 121.]]


In [57]:
print(np.max(ar2))

99


In [58]:
print(np.min(ar2))

11


In [59]:
print(np.var(ar2))

806.6666666666666


In [60]:
print(np.std(ar2))

28.401877872187722


In [61]:
print(np.power(ar2,2))

[[ 121  484 1089]
 [1936 3025 4356]
 [5929 7744 9801]]


In [62]:
print(np.sqrt(ar2))

[[3.31662479 4.69041576 5.74456265]
 [6.63324958 7.41619849 8.1240384 ]
 [8.77496439 9.38083152 9.94987437]]


In [63]:
print(np.abs(ar2))

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [64]:
print(np.sin(ar2))

[[-0.99999021 -0.00885131  0.99991186]
 [ 0.01770193 -0.99975517 -0.02655115]
 [ 0.99952016  0.0353983  -0.99920683]]


In [65]:
print(np.cos(ar2))

[[ 0.0044257  -0.99996083 -0.01327675]
 [ 0.99984331  0.02212676 -0.99964746]
 [-0.03097503  0.99937328  0.03982088]]


In [66]:
print(np.tan(ar2))

[[-2.25950846e+02  8.85165604e-03 -7.53130148e+01]
 [ 1.77046993e-02 -4.51830879e+01  2.65605178e-02]
 [-3.22685758e+01  3.54205013e-02 -2.50925350e+01]]


In [67]:
print(np.log(ar2))

[[2.39789527 3.09104245 3.49650756]
 [3.78418963 4.00733319 4.18965474]
 [4.34380542 4.47733681 4.59511985]]


In [68]:
print(np.log10(ar2))

[[1.04139269 1.34242268 1.51851394]
 [1.64345268 1.74036269 1.81954394]
 [1.88649073 1.94448267 1.99563519]]


In [69]:
print(np.exp(ar2))

[[5.98741417e+04 3.58491285e+09 2.14643580e+14]
 [1.28516001e+19 7.69478527e+23 4.60718663e+28]
 [2.75851345e+33 1.65163625e+38 9.88903032e+42]]


In [89]:
a=np.array([range(25,34)])
a

array([[25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [93]:
a22=np.arange(25,34)
a22

array([25, 26, 27, 28, 29, 30, 31, 32, 33])

**Relational operator**




In [3]:
a1=np.array([215,323,520,636,717,281,162,411])
a2=np.array([311,453,520,362,230,281,672,891])


print("Comparing corresponding elements of two arrays\n",a1>=a2)

print("Comparing corresponding elements of two arrays\n",a1<=a2)

print("Comparing corresponding elements of two arrays\n",a1==a2)

print("Comparing corresponding elements of two arrays\n",a1!=a2)


Comparing corresponding elements of two arrays
 [False False  True  True  True  True False False]
Comparing corresponding elements of two arrays
 [ True  True  True False False  True  True  True]
Comparing corresponding elements of two arrays
 [False False  True False False  True False False]
Comparing corresponding elements of two arrays
 [ True  True False  True  True False  True  True]
