In [41]:
import numpy as np
    

In [42]:
arr=np.array([13,42,45,32,78,12,98,34,23,12,87,43,9])

In [43]:
arr

array([13, 42, 45, 32, 78, 12, 98, 34, 23, 12, 87, 43,  9])

In [44]:
arr[5]=21
arr

array([13, 42, 45, 32, 78, 21, 98, 34, 23, 12, 87, 43,  9])

In [45]:
print(np.size(arr))

13


In [46]:
print(np.shape(arr))

(13,)


In [47]:
print(arr.dtype)

int32


In [48]:
print(np.mean(arr))
print(np.median(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.var(arr))
print(np.cov(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

41.30769230769231
34.0
537
878737408
788.9822485207102
854.7307692307692
28.088827823900203
98
9


In [49]:
print(np.sort(arr))

[ 9 12 13 21 23 32 34 42 43 45 78 87 98]


In [50]:
print(np.sqrt(arr))
print(np.power(arr,3))
arr2=np.array([21,-23,-45,66,99,76])
print(np.abs(arr2))

[3.60555128 6.4807407  6.70820393 5.65685425 8.83176087 4.58257569
 9.89949494 5.83095189 4.79583152 3.46410162 9.32737905 6.55743852
 3.        ]
[  2197  74088  91125  32768 474552   9261 941192  39304  12167   1728
 658503  79507    729]
[21 23 45 66 99 76]


In [51]:
arr3=np.arange(20,40,2)
arr3

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [52]:
print(arr3+8)

[28 30 32 34 36 38 40 42 44 46]


In [53]:
print(arr3-5)

[15 17 19 21 23 25 27 29 31 33]


In [54]:
print(arr3*3)

[ 60  66  72  78  84  90  96 102 108 114]


In [55]:
print(arr3/3) #division

[ 6.66666667  7.33333333  8.          8.66666667  9.33333333 10.
 10.66666667 11.33333333 12.         12.66666667]


In [56]:
print(arr3//3) #quotient

[ 6  7  8  8  9 10 10 11 12 12]


In [57]:
print(arr3%3) #reamainder

[2 1 0 2 1 0 2 1 0 2]


**Relational operator**

In [68]:
a1=np.array([215,323,520,636,717,281,162,411])
a2=np.array([311,453,520,362,230,281,672,891])


In [69]:
print("Comparing corresponding elements of two arrays\n",a1>=a2)

Comparing corresponding elements of two arrays
 [False False  True  True  True  True False False]


In [70]:
print("Comparing corresponding elements of two arrays\n",a1<=a2)

Comparing corresponding elements of two arrays
 [ True  True  True False False  True  True  True]


In [71]:
print("Comparing corresponding elements of two arrays\n",a1==a2)

Comparing corresponding elements of two arrays
 [False False  True False False  True False False]


In [72]:
print("Comparing corresponding elements of two arrays\n",a1!=a2)

Comparing corresponding elements of two arrays
 [ True  True False  True  True False  True  True]
