# Numpy

In [8]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print("The array is", (arr));
print(arr[0])
print(arr[1])

The array is [1 2 3 4]
1
2


In [10]:
import numpy as np
myarray1= np.array ([11,22,33,44.4,55,66], int)
myarray2= np.array(['a','b','c','d','e','f'])
dtype=str
myarray3= np.array(['java','datastruct','javas','maths','automata'])
# print("The array is", (myarray1));
# print("The array is", (myarray2));
# print("The array is", (myarray3));
myarray4= np.array ([11.2,22.2,33.4,44.4,55.5,66.7], float)
myarray5=myarray3.view();
print("using view function to create a new array ",myarray5)
myarray6=myarray2.copy();
print("using copy function to create a new array ",myarray6)


using view function to create a new array  ['java' 'datastruct' 'javas' 'maths' 'automata']
using copy function to create a new array  ['a' 'b' 'c' 'd' 'e' 'f']


In [11]:
import numpy
myarray7=numpy.arange(14)
print("array is",myarray7)

array is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [12]:
import numpy
myarray8=numpy.arange(14,19,dtype = numpy.float)
print("array is",myarray8)


array is [14. 15. 16. 17. 18.]


C:\Users\ind\AppData\Local\Temp\ipykernel_16244\2649470491.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  myarray8=numpy.arange(14,19,dtype = numpy.float)


In [13]:
import numpy
myarray9=numpy.linspace(12,24,5)
print("array is",myarray9)

array is [12. 15. 18. 21. 24.]


In [14]:
import numpy
myarray10=numpy.linspace(1.,4.,5)
print("array is",myarray10)

array is [1.   1.75 2.5  3.25 4.  ]


In [15]:
import numpy
myarray11=numpy.zeros((4))
print("array is",myarray11)

array is [0. 0. 0. 0.]


In [16]:
import numpy
myarray12=numpy.ones((4))
print("array is",myarray12)
myarray12[2]=45;
print("modified array is",myarray12)
print(myarray12.size)
print(myarray12.dtype)
print(numpy.mean(myarray12))
print(numpy.median(myarray12))
print(numpy.max(myarray12))
print(numpy.min(myarray12))
print(numpy.sum(myarray12))
#  product
print(numpy.prod(myarray12))
# covarience
print(numpy.cov(myarray12))
# standard deviation
print(numpy.std(myarray12))
# variance
print(numpy.var(myarray12))


array is [1. 1. 1. 1.]
modified array is [ 1.  1. 45.  1.]
4
float64
12.0
1.0
45.0
1.0
48.0
45.0
484.0
19.05255888325765
363.0


In [21]:
# absolute value
print(numpy.abs(myarray12))
# square root
print(numpy.sqrt(myarray12))
print(numpy.sin(myarray12))
print(numpy.cos(myarray12))
print(numpy.log(myarray12))
print(numpy.log10(myarray12))
# exponential
print(numpy.exp(myarray12))
print(numpy.log(myarray12))
print(numpy.log10(myarray12))
print(numpy.exp(myarray12))

[ 1.  1. 45.  1.]
[1.         1.         6.70820393 1.        ]
[0.84147098 0.84147098 0.85090352 0.84147098]
[0.54030231 0.54030231 0.52532199 0.54030231]
[0.         0.         3.80666249 0.        ]
[0.         0.         1.65321251 0.        ]
[2.71828183e+00 2.71828183e+00 3.49342711e+19 2.71828183e+00]
[0.         0.         3.80666249 0.        ]
[0.         0.         1.65321251 0.        ]
[2.71828183e+00 2.71828183e+00 3.49342711e+19 2.71828183e+00]


In [19]:
#log() functionn return the log with exponential base
import numpy
print(numpy.log(myarray12))

[0.         0.         3.80666249 0.        ]


In [26]:
#mathematical operations on one dimensional array.
myarray12=numpy.arange(25,34)
print("Original array is ",myarray12)
print("Adding an element to array elements :",myarray12+12)
# Above operation is known as BROADCASTING
print("Subtracting an element to array elements : ",myarray12-9)
print("Multiplying an element to array elements : ",myarray12*9)
print("Dividing an element to array elements : ",myarray12/9)
print("Using modulus operator for the array elements : ",myarray12%23)
print("Using integer division for the array elements : ",myarray12//2)



Original array is  [25 26 27 28 29 30 31 32 33]
Adding an element to array elements : [37 38 39 40 41 42 43 44 45]
Subtracting an element to array elements :  [16 17 18 19 20 21 22 23 24]
Multiplying an element to array elements :  [225 234 243 252 261 270 279 288 297]
Dividing an element to array elements :  [2.77777778 2.88888889 3.         3.11111111 3.22222222 3.33333333
 3.44444444 3.55555556 3.66666667]
Using modulus operator for the array elements :  [ 2  3  4  5  6  7  8  9 10]
Using integer division for the array elements :  [12 13 13 14 14 15 15 16 16]


In [30]:
#program to use mathematical operators on multiple arrays.
import numpy as np
#creating three integer array
myarray15=np.array([11,22,33],int)
myarray16=np.array([40,50,60],int)
myarray17=np.array([7,8,9],int)

#performing addition and subtraction on all elements of an array
myarray18 = myarray17 + myarray16 - myarray15
print("Addition and subtraction on multiple arrays : ",myarray18)

#performing multiplication and division on all elements of an array. 
myarray19=(myarray15*myarray16)/myarray17
print("Multiplication and division on multiple arrays : ",myarray19)
print(len(str(myarray19[1])))

#using modulus operator on all elements of an array.
myarray20=myarray16%myarray17
print("using modulus operator on two arrays : ",myarray20)





Addition and subtraction on multiple arrays :  [36 36 36]
Multiplication and division on multiple arrays :  [ 62.85714286 137.5        220.        ]
5
using modulus operator on two arrays :  [5 2 6]


In [29]:
#program to show creation of multidimensional array.
import numpy as np
#creating a two-dimensional array using array() function.
mymultarray1=np.array([[100,200,300,400],[600,700,800,900]])
print("multidimensional array using array function is: \n",mymultarray1)

#creating a two-dimensional array using matrix() function.
mymultarray2=np.matrix("11 22; 33 44; 55 66")
print("multidimensional array using matrix function is: \n",mymultarray2)

#creating a two-dimensional array using reshape() function.
newarray=np.array([10,20,30,40,50,60])
mymultarray3=np.reshape(newarray,(3,2))
print("multidimensional array using reshape function is: \n",mymultarray3)

#creating array using zeros() function.
mymultarray4=np.zeros((4,2))
print("multidimesional array using zeros function is: \n",mymultarray4)

#creating array using ones() function.
mymultarray5=np.ones((2,3))
print("multidimensional array using ones function is: \n",mymultarray5)







multidimensional array using array function is: 
 [[100 200 300 400]
 [600 700 800 900]]
multidimensional array using matrix function is: 
 [[11 22]
 [33 44]
 [55 66]]
multidimensional array using reshape function is: 
 [[10 20]
 [30 40]
 [50 60]]
multidimesional array using zeros function is: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
multidimensional array using ones function is: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
#program to show indexing in multidimensional arrays.
import numpy as np
mymultarray6=np.reshape(range(100,400,50),(3,2))
print("the array is: \n",mymultarray6)

#performing indexing
print("element of first row and second column is: ",mymultarray6[0][1])
print("element of second row and first column is: ",mymultarray6[1][0])
print("element of second row and second column is: ",mymultarray6[1][1])
print("element of third row and first column is: ",mymultarray6[2][0])
print("element of third row and second column is: ",mymultarray6[2][1])



the array is: 
 [[100 150]
 [200 250]
 [300 350]]
element of first row and second column is:  150
element of second row and first column is:  200
element of second row and second column is:  250
element of third row and first column is:  300
element of third row and second column is:  350


In [3]:
#program to show slicing in multidimensional array.
import numpy as np
mymultarray7=np.reshape(range(100,500,20),(4,5))
print("the multidimensional array is: \n",mymultarray7[:,:])

#slicing by specifying only row indexes.
print("first two rows are: \n",mymultarray7[0:2,])
print("third row is: \n",mymultarray7[2,])

#slicing by specifying both the row and column indexes.
print("elements in first and second row and column are: \n",mymultarray7[0:2,0:2])
print("elements in second row and second to fourth column are: \n",mymultarray7[1,1:4])


the multidimensional array is: 
 [[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
first two rows are: 
 [[100 120 140 160 180]
 [200 220 240 260 280]]
third row is: 
 [300 320 340 360 380]
elements in first and second row and column are: 
 [[100 120]
 [200 220]]
elements in second row and second to fourth column are: 
 [220 240 260]


In [16]:
#functions on multidimensional array
#program for functions on multidimensional array.
import numpy as np
mymultarray8=np.array([[10,60,40],[40,50,30],[50,60,40],[40,50,20]])
#displaying the matrix
print("the original matrix is: \n",mymultarray8)
#the transpose() function returns the transpose of a matrix.
print("tansposed matrix is:\n ",mymultarray8.transpose())
#the ndim determines dimensions of the array.
print("dimension of the array is: ",mymultarray8.ndim)
#the shape determines shape of the array.
print("shape of the array is: ",mymultarray8.shape)
#the flatten() flattens the matrix and converts into one-dimensional.
print("flattened matrix is: \n",mymultarray8.flatten())
#the sort() function with axis=1 (default)sorts the matrix on row basis.
print("sorted matrix on row basis(default):\n ",np.sort(mymultarray8))
#the sort() function with axis=0 sorts the matrix on column basis.
print("sorted matrix on columnar basis: \n",np.sort(mymultarray8,axis=0))
#the diagonal() function helps to determine the diagonal elements.
print("diagonal elements are: ",np.diagonal(mymultarray8))

the original matrix is: 
 [[10 60 40]
 [40 50 30]
 [50 60 40]
 [40 50 20]]
tansposed matrix is:
  [[10 40 50 40]
 [60 50 60 50]
 [40 30 40 20]]
dimension of the array is:  2
shape of the array is:  (4, 3)
flattened matrix is: 
 [10 60 40 40 50 30 50 60 40 40 50 20]
sorted matrix on row basis(default):
  [[10 40 60]
 [30 40 50]
 [40 50 60]
 [20 40 50]]
sorted matrix on columnar basis: 
 [[10 50 20]
 [40 50 30]
 [40 60 40]
 [50 60 40]]
diagonal elements are:  [10 50 40]


In [28]:
#mathematical operators for multiple multidimensional array
#program for using basic mathematical operators on multidimensional array.
import numpy as np
mymultarray9=np.array([[10,20,30,40],[50,60,70,80]])
mymultarray10=np.array([11,22,33,44,55,66,77,88])
mymultarray10=np.reshape(mymultarray10,(2,4))

#mathematical operations between multidimensional arrays.
print("addition of 2-d arrays: \n",mymultarray9+mymultarray10)
print("subtration of 2-d arrays: \n",mymultarray9-mymultarray10)
print("multiplication of 2-d arrays: \n",mymultarray9*mymultarray10)
print("division of 2-d arrays: \n",mymultarray9/mymultarray10)
print("modulus operator for 2-d arrays: \n",mymultarray9%mymultarray10)
print("integer division on 2-d arrays: \n",mymultarray9//mymultarray10)

#matrix multiplication.
mymultarray11=np.matrix("10 12; 14 10; 12 10; 14 20")
print("matrix multiplication:\n",mymultarray10*mymultarray11)

addition of 2-d arrays: 
 [[ 21  42  63  84]
 [105 126 147 168]]
subtration of 2-d arrays: 
 [[-1 -2 -3 -4]
 [-5 -6 -7 -8]]
multiplication of 2-d arrays: 
 [[ 110  440  990 1760]
 [2750 3960 5390 7040]]
division of 2-d arrays: 
 [[0.90909091 0.90909091 0.90909091 0.90909091]
 [0.90909091 0.90909091 0.90909091 0.90909091]]
modulus operator for 2-d arrays: 
 [[10 20 30 40]
 [50 60 70 80]]
integer division on 2-d arrays: 
 [[0 0 0 0]
 [0 0 0 0]]
matrix multiplication:
 [[1430 1562]
 [3630 3850]]
