In [14]:
import numpy as np

In [18]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
a2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 144],
       [169, 196, 225, 256]])

In [19]:
b2=np.array([[10,10,10,10],[11,11,11,11],[12,12,12,12],[13,13,13,13]])
b2

array([[10, 10, 10, 10],
       [11, 11, 11, 11],
       [12, 12, 12, 12],
       [13, 13, 13, 13]])

**QUES 1 Find transpose of a2**

In [22]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
a2=np.transpose(a2)
a2

array([[ 11,  55,  99, 169],
       [ 22,  66, 110, 196],
       [ 33,  77, 121, 225],
       [ 44,  88, 144, 256]])

**Ques 2 Perform ,Addition,Subtraction and Multiplication of two arrays**

In [23]:
def add(a2,b2):
    if(a2.shape==b2.shape):
        return a2+b2
    else:
        return "dimension of a2 and b2 doesnt match"
print(add(a2,b2))

[[ 21  65 109 179]
 [ 33  77 121 207]
 [ 45  89 133 237]
 [ 57 101 157 269]]


In [24]:
def sub(a2,b2):
    if(a2.shape==b2.shape):
        return a2-b2
    else:
        return "dimension of a2 and b2 doesnt match"
print(sub(a2,b2))

[[  1  45  89 159]
 [ 11  55  99 185]
 [ 21  65 109 213]
 [ 31  75 131 243]]


In [25]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144]])
b2=np.array([[10,10,10],[11,11,11],[12,12,12],[13,13,13]])
print("Matrix A:\n",a2)
print("Matrix B:\n",b2)
r,c=np.shape(a2)
print("shape of A(",r,",",c,")")
r1,c1=np.shape(b2)
print("shape of B(",r1,",",c1,")")
if c==r1:
    print("Multiplication of matrix A*B :\n",a2.dot(b2))
    print("With dimension(",r,",",c1,")")
else:
    print("Multiplication is not possible")


Matrix A:
 [[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 144]]
Matrix B:
 [[10 10 10]
 [11 11 11]
 [12 12 12]
 [13 13 13]]
shape of A( 3 , 4 )
shape of B( 4 , 3 )
Multiplication of matrix A*B :
 [[1320 1320 1320]
 [3344 3344 3344]
 [5524 5524 5524]]
With dimension( 3 , 3 )


In [26]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144]])
b2=np.array([[10,10,10],[11,11,11],[12,12,12]])
print("Matrix A:\n",a2)
print("Matrix B:\n",b2)
r,c=np.shape(a2)
print("shape of A(",r,",",c,")")
r1,c1=np.shape(b2)
print("shape of B(",r1,",",c1,")")
if c==r1:
    print("Multiplication of matrix A*B :\n",a2.dot(b2))
    print("With dimension(",r,",",c1,")")
else:
    print("Multiplication is not possible")
    print("As (column of A)!=(row of B)")

Matrix A:
 [[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 144]]
Matrix B:
 [[10 10 10]
 [11 11 11]
 [12 12 12]]
shape of A( 3 , 4 )
shape of B( 3 , 3 )
Multiplication is not possible
As (column of A)!=(row of B)


**Ques 3 Find the trace (sum of diagonal elements) of a square matrix**

In [28]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144]])
T=np.trace(a2)
print(T)

198


In [33]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
r,c=np.shape(a2)
T=0
for i in range(0,r):
    for j in range(0,c):
        if i==j:
            T=T+a2[i][j]
print("Trace of\n",a2,"\nis",T)

Trace of
 [[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 144]
 [169 196 225 256]] 
is 454


**Ques 4 Convert the given matrix into an identity matrix**

In [36]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
r,c=np.shape(a2)
for i in range(0,r):
    for j in range(0,c):
        if i==j:
            continue
        else:
            a2[i][j]=0
print("Matrix a2 as identity matrix\n",a2)

Matrix a2 as identity matrix
 [[ 11   0   0   0]
 [  0  66   0   0]
 [  0   0 121   0]
 [  0   0   0 256]]


In [37]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
r,c=np.shape(a2)
for i in range(0,r):
    for j in range(0,c):
        if i==j:
            a2[i][j]=1
        else:
            a2[i][j]=0
print("Matrix a2 as identity matrix\n",a2)

Matrix a2 as identity matrix
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Ques 5 Convert the given matrix into an upper triangular matrix**

In [38]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
r,c=np.shape(a2)
for i in range(0,r):
    for j in range(0,c):
        if j>i:
            continue
        else:
            a2[i][j]=0
print("Upper Triangular Matrix\n",a2)

Upper Triangular Matrix
 [[  0  22  33  44]
 [  0   0  77  88]
 [  0   0   0 144]
 [  0   0   0   0]]


In [39]:
a2=np.array([[11,22,33,44],[55,66,77,88],[99,110,121,144],[169,196,225,256]])
r,c=np.shape(a2)
for i in range(0,r):
    for j in range(0,c):
        if j<i:
            continue
        else:
            a2[i][j]=0
print("Lower Triangular Matrix\n",a2)

Lower Triangular Matrix
 [[  0   0   0   0]
 [ 55   0   0   0]
 [ 99 110   0   0]
 [169 196 225   0]]
