### Ques ) Concatenation

In [2]:
import numpy as np

In [3]:
Sales=np.array([[40,32,45,50,35],[43,44,47,32,38],[34,50,48,39,29],[26,38,40,48,44],[34,39,47,44,45],[45,34,28,50,48],[50,40,39,49,50]])
D=np.array([["DAY"],["Mon"],["Tue"],["Wed"],["Thu"],["Fri"],["Sat"],["Sun"],])
P=np.array([[" P1 "],[" P2 "],[" P3 "],[" P4 "],[" P5 "],[" AvgD"]])
P.resize(1,6)
print("Table of sales\n",Sales)
print("_______________________________________________________________________________________________________________________")
avgD=[] #average sales on a paticular day
for i in Sales:
    avgD.append(np.mean(i))   
avgD_n=np.array(avgD)
avgD_n.resize(7,1)
print("average of sales each day\n",avgD_n)
print("_______________________________________________________________________________________________________________________")
f=np.concatenate((Sales,avgD_n),axis=1)
print("Table of sales and average of sales each day\n",f)
print("_______________________________________________________________________________________________________________________")
f1=np.concatenate((P,f),axis=0)
print("Table of sales and average of sales each day\n",f1)
print("_______________________________________________________________________________________________________________________")
f2=np.concatenate((D,f1),axis=1)
print("Table of sales and average of sales each day\n",f2)

Table of sales
 [[40 32 45 50 35]
 [43 44 47 32 38]
 [34 50 48 39 29]
 [26 38 40 48 44]
 [34 39 47 44 45]
 [45 34 28 50 48]
 [50 40 39 49 50]]
_______________________________________________________________________________________________________________________
average of sales each day
 [[40.4]
 [40.8]
 [40. ]
 [39.2]
 [41.8]
 [41. ]
 [45.6]]
_______________________________________________________________________________________________________________________
Table of sales and average of sales each day
 [[40.  32.  45.  50.  35.  40.4]
 [43.  44.  47.  32.  38.  40.8]
 [34.  50.  48.  39.  29.  40. ]
 [26.  38.  40.  48.  44.  39.2]
 [34.  39.  47.  44.  45.  41.8]
 [45.  34.  28.  50.  48.  41. ]
 [50.  40.  39.  49.  50.  45.6]]
_______________________________________________________________________________________________________________________
Table of sales and average of sales each day
 [[' P1 ' ' P2 ' ' P3 ' ' P4 ' ' P5 ' ' AvgD']
 ['40.0' '32.0' '45.0' '50.0' '35.0' '40.4'